gems:
    - jekyll-paginate
    - jekyll-redirect-from

paginate: 4
paginate_path: "/blog/:num/"

social:
    facebook: "https://www.facebook.com/pages/Team-334-TechKnights/116920961670659?sk=timeline"
    twitter: "https://twitter.com/techknights334"
    instagram: "http://www.instagram.com/robotics_team_334/"
    github: "https://github.com/Team334"
